# -*- coding: utf-8 -*-
"""3.1_The_Two_Num_Types.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xu5E7_iJKIXokB4pG0zNIKam8mVcnHsD

*  int = whole number, no decimal

* Float = has a decimal point
"""

tablet = 30
price = 12.75
temperature = 37.0

print(type(tablet))
print(type(price))

"""37.0 is also a float even though it ends in .0"""