# -*- coding: utf-8 -*-
"""3.2_Math_Operator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j5MaU3qmzzJI4wnzRuZ57qURc4IhTR7F

1)Learn Operator like Addition(+), Substraction(-), Multiplication(*), division(/), Floor division(//), Reminder (%), Power(**).

2)In This:-

* Regular division always gives a float.

* Floor division rounds down to whole number.

* Reminder gives what's left after dividing.

* Power multiply a number by itself n times.
"""

# ========== DOSE CALCULATOR ==========
weight_kg = 70
dose_per_kg = 15
frequency = 3
days = 7

single_dose = weight_kg * dose_per_kg
daily_dose = single_dose * frequency
total_dose = daily_dose * days
print(f"Single dose  : {single_dose}mg")
print(f"Daily dose   : {daily_dose}mg")
print(f"Total (7days): {total_dose}mg")